#!/usr/bin/env bash

# Get the files in the current directory (excluding hidden files)

files=$(ls -p | grep -v / | grep -v "^\.")

# Loop through each file and display the part of the name after the first dash
for file in $files
do
  name=$(echo "$file" | cut -d'-' -f2-)
  echo "$name"
done
